server {
    listen 80;
    server_name localhost;

    # Sirve los archivos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Fundamental para React Router
    }

    # Redirige las peticiones /api/ al contenedor del backend
    location /api/ {
        proxy_pass http://opcua-linker-backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}